### ISSUE TITLE
Python broken in nightlies

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/key4hep-spack#495]
```
[lreichen@pcphsft121 test]$ . /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh 
AlmaLinux 9 detected
Setting up the latest Key4HEP software stack from CVMFS ...
 ...  Key4HEP release: 2023-06-05
 ...  Use the following command to reproduce the current environment: 
 ... 
         source /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-06-05/x86_64-almalinux9-gcc11.3.1-opt/key4hep-stack/2023-06-05-xkq5t2/setup.sh
 ... 
 ...  If you have any issues, comments or requests open an issue at https://github.com/key4hep/key4hep-spack/issues
[lreichen@pcphsft121 test]$ k4run -l
Traceback (most recent call last):
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-06-05/x86_64-almalinux9-gcc11.3.1-opt/k4fwcore/348be068b687353f2886421110190aaa682bd293=develop-qp5dqa/bin/k4run", line 113, in <module>
    opts = parser.parse_known_args()
  File "/usr/lib64/python3.9/argparse.py", line 1858, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.9/argparse.py", line 2070, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib64/python3.9/argparse.py", line 2026, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.9/argparse.py", line 1935, in take_action
    action(self, namespace, argument_values, option_string)
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-06-05/x86_64-almalinux9-gcc11.3.1-opt/k4fwcore/348be068b687353f2886421110190aaa682bd293=develop-qp5dqa/bin/k4run", line 37, in __call__
    for conf in dict.fromkeys(ApplicationMgr.allConfigurables.values()):
NameError: name 'ApplicationMgr' is not defined
```

**Comment by jmcarcell** [comment]
I think the easiest workaround that doesn't break other things is to get a local copy of k4run and change python to python3 in the first line. It may be possible by removing `/usr/bin` and other paths from `$PATH` but that would break system packages

**Comment by Zehvogel** [comment]
Oh yes looking at the error message more carefully I get the same impression, changed the tilte now ;)

**Comment by jmcarcell** [comment]
Fixed in the latest nightlies
