### ISSUE TITLE
Incompatible ROOT and numpy versions

### ISSUE THREAD

**Issue by gartrog** [key4hep/key4hep-spack#497]
Hello,

In the latest release from April as well as in the nightlies, there is some incompatibility between the numpy and the ROOT versions.

More specifically: when trying to use the `AsNumpy` function of a RDataFrame, it complains:
```
/cvmfs/sw.hsf.org/spackages7/root/6.26.10/x86_64-centos7-gcc11.2.0-opt/i4xdf/lib/root/ROOT/_pythonization/_rdataframe.py:138: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  tmp = numpy.empty(len(cpp_reference), dtype=numpy.object)
Traceback (most recent call last):
  File "/users/atlas/morange/EventDisplays.py", line 316, in <module>
    main()
  File "/users/atlas/morange/EventDisplays.py", line 212, in main
    arr = d1.AsNumpy(["z1_phi", "z1_theta", "z1_energy", "z2_phi", "z2_theta", "z2_energy",
  File "/cvmfs/sw.hsf.org/spackages7/root/6.26.10/x86_64-centos7-gcc11.2.0-opt/i4xdf/lib/root/ROOT/_pythonization/_rdataframe.py", line 87, in RDataFrameAsNumpy
    return result.GetValue()
  File "/cvmfs/sw.hsf.org/spackages7/root/6.26.10/x86_64-centos7-gcc11.2.0-opt/i4xdf/lib/root/ROOT/_pythonization/_rdataframe.py", line 138, in GetValue
    tmp = numpy.empty(len(cpp_reference), dtype=numpy.object)
  File "/cvmfs/sw.hsf.org/spackages7/py-numpy/1.24.2/x86_64-centos7-gcc11.2.0-opt/3afgv/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'object_'?
```

This would be fixed by upgrading to ROOT 6.28/04, see
https://github.com/root-project/root/issues/12148
or by downgrading numpy < 1.24

**Comment by jmcarcell** [comment]
Workaround for now (tested on Alma9):
``` bash
pip install --user numpy==1.23
export PYTHONPATH=~/.local/lib/python3.10/site-packages:$PYTHONPATH
```
I'll post here again once this is fixed in the nightlies. Given the number of packages we'll make a build from scratch (ideally with a newer ROOT instead of pinning numpy) soonish, hopefully this week

Code to reproduce:
``` python
import ROOT
df = ROOT.RDataFrame(10) \
         .Define("x", "(int)rdfentry_") \
         .Define("y", "1.f/(1.f+rdfentry_)")
ROOT.gInterpreter.Declare("""
// Inject the C++ class CustomObject in the C++ runtime.
class CustomObject {
public:
    int x = 42;
};
// Create a function that returns such an object. This is called to fill the dataframe.
CustomObject fill_object() { return CustomObject(); }
""")

df3 = df.Define("custom_object", "fill_object()")
npy5 = df3.AsNumpy()
print("Read-out of C++ objects:\n{}\n".format(npy5["custom_object"]))
print("Access to all methods and data members of the C++ object:\nObject: {}\nAccess data member: custom_object.x = {}\n".format(
    repr(npy5["custom_object"][0]), npy5["custom_object"][0].x))
```

**Comment by gartrog** [comment]
Thanks ! The workaround works perfectly for us !

**Comment by jmcarcell** [comment]
This has been solved in the nightlies, where we have now ROOT 6.28/04
