### ISSUE TITLE
Fail to create Geant4Output2EDM4hep in the nightlies

### ISSUE THREAD

**Issue by BrieucF** [key4hep/key4hep-spack#500]
Sourcing the nightlies on lxplus and trying to run `ddsim` with edm4hep output fails due to:

```
Geant4Handle     ERROR Failed to create object of type Geant4Output2EDM4hep!
Traceback (most recent call last):
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-06-20/x86_64-centos7-gcc12.2.0-opt/dd4hep/1.23-lammpf/bin/ddsim", line 25, in <module>
    RUNNER.run()
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-06-20/x86_64-centos7-gcc12.2.0-opt/dd4hep/1.23-lammpf/lib/python3.10/site-packages/DDSim/DD4hepSimulation.py", line 365, in run
    e4Out = simple.setupEDM4hepOutput('EDM4hepOutput', self.outputFile)
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-06-20/x86_64-centos7-gcc12.2.0-opt/dd4hep/1.23-lammpf/lib/python3.10/site-packages/DDG4.py", line 807, in setupEDM4hepOutput
    evt_edm4hep = EventAction(self.kernel(), 'Geant4Output2EDM4hep/' + name, True)
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-06-20/x86_64-centos7-gcc12.2.0-opt/dd4hep/1.23-lammpf/lib/python3.10/site-packages/DDG4.py", line 197, in EventAction
    return Interface.createEventAction(kernel, str(nam), shared)
cppyy.gbl.std.runtime_error: static dd4hep::sim::EventActionHandle dd4hep::sim::Geant4ActionCreation::createEventAction(dd4hep::sim::KernelHandle& kernel, const string& name_type, bool shared) =>
    runtime_error: Geant4Handle: Failed to create object of type Geant4Output2EDM4hep!
```

To reproduce the error:
```
source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
ddsim --compactFile $FCCDETECTORS/Detector/DetFCCeeCLD/compact/FCCee_o2_v02/FCCee_o2_v02.xml --enableGun --gun.distribution uniform --gun.energy "10*GeV" --gun.particle mu- --numberOfEvents 100 --outputFile Step1_edm4hep.root
```

**Comment by andresailer** [comment]
Something turned off the EDM4hep plugin
/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-06-20/x86_64-centos7-gcc12.2.0-opt/dd4hep/1.23-lammpf/.spack/spack-build-01-cmake-out.txt
```
' '-DDD4HEP_USE_EDM4HEP:BOOL=OFF' 
```

**Comment by jmcarcell** [comment]
Well, at some point the develop versions of podio and DD4hep (pinned to 1.23) were incompatible when building DD4hep with EDM4hep so I disabled it "temporarily" because the Frame was going to be merged "very soon". Of course I forgot and we had this for a while. Now this has been fixed in the nightlies and we have the latest version of DD4hep with EDM4hep.
